apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cds-db
  name: cds-db
  namespace: cds 
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cds-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cds-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: cds
            - name: POSTGRES_PASSWORD
              value: cds
            - name: POSTGRES_USER
              value: cds
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          image: postgres:14.0
          name: cds-db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: cds-postgres-volume
      restartPolicy: Always
      volumes:
        - name: cds-postgres-volume
          persistentVolumeClaim:
            claimName: cds-postgres-volume
status: {}
