apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cds-cdn
  name: cds-cdn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cds-cdn
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cds-cdn
    spec:
      containers:
        - args:
            - sh
            - -c
            - /app/cds-engine-linux-amd64 start cdn --config /app/conf/conf.toml
          image: ovhcom/cds-engine:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://127.0.0.1:8089/mon/version
            failureThreshold: 6
            periodSeconds: 30
            timeoutSeconds: 10
          name: cds-cdn
          ports:
            - containerPort: 8089
            - containerPort: 8090
          resources: {}
          volumeMounts:
            - mountPath: /app/conf
              name: cds-conf-volume
            - mountPath: /app/cdn-buffer
              name: cds-cdn-buffer-volume
            - mountPath: /app/cdn-storage
              name: cds-cdn-storage-volume
      restartPolicy: Always
      volumes:
        - name: cds-conf-volume
          persistentVolumeClaim:
            claimName: cds-conf-volume
        - name: cds-cdn-buffer-volume
          persistentVolumeClaim:
            claimName: cds-cdn-buffer-volume
        - name: cds-cdn-storage-volume
          persistentVolumeClaim:
            claimName: cds-cdn-storage-volume
status: {}
