apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cds-elasticsearch
  name: cds-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cds-elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cds-elasticsearch
    spec:
      containers:
        - args:
            - sh
            - -c
            - /app/cds-engine-linux-amd64 start elasticsearch --config /app/conf/conf.toml
          image: ovhcom/cds-engine:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://127.0.0.1:8088/mon/version
            failureThreshold: 6
            periodSeconds: 30
            timeoutSeconds: 10
          name: cds-elasticsearch
          resources: {}
          volumeMounts:
            - mountPath: /app/conf
              name: cds-conf-volume
      restartPolicy: Always
      volumes:
        - name: cds-conf-volume
          persistentVolumeClaim:
            claimName: cds-conf-volume
status: {}
